# Generated by Django 4.0.1 on 2022-01-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_account_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='paid_amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='paid',
            new_name='received_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
